version: '3'

services:
  selenium-hub:
    image: selenium/hub
    ports:
      - "6666-6668:6666-6668"
    networks:
      - grid
     
  node-chrome:
    image: selenium/node-chrome
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=6666
      - SE_EVENT_BUS_SUBSCRIBE_PORT=6668
    networks:
      - grid

  node-firefox:
    image: selenium/node-firefox
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=6666
      - SE_EVENT_BUS_SUBSCRIBE_PORT=6668
    networks:
      - grid 
      
networks:
  grid:
    driver: bridge